### ISSUE TITLE
[CircularUI][CircleListView] Custom DataTemplate issue

### ISSUE THREAD

**Issue by t-zalewski** [Samsung/Tizen.CircularUI#103]
Hi,

I want to use a ViewCell in custom DataTemplate for a CircleListView. Problem is that CircleListView is not focusing first and last item on the list (however, I can Tap the items but without focus it could be sometimes confusing).

 ```XML
 <w:CircleListView.ItemTemplate>
      <DataTemplate>
          <ViewCell>
              <StackLayout Orientation="Horizontal">
                  <Image Source="ViewCell.png"/>
                  <Label Text="{Binding .}"
                         HorizontalTextAlignment="Center"/>
              </StackLayout>
          </ViewCell>
      </DataTemplate>
  </w:CircleListView.ItemTemplate>
```

![unfocusedfirstsmall](https://user-images.githubusercontent.com/11194646/44709748-e5fbc200-aa99-11e8-988b-dd78726acf13.png)
![unfocusedlastsmall](https://user-images.githubusercontent.com/11194646/44709750-e5fbc200-aa99-11e8-8ff7-705e32749412.png)

Situation changes a little bit when i set WidthRequest property for the items in StackLayout.
```XML
<w:CircleListView.ItemTemplate>
    <DataTemplate>
        <ViewCell>
            <StackLayout Orientation="Horizontal">
                <Image Source="ViewCell.png"
                       HeightRequest="100"/>
                <Label Text="{Binding .}"
                       HorizontalTextAlignment="Center"
                       HeightRequest="100"/>
            </StackLayout>
        </ViewCell>
    </DataTemplate>
</w:CircleListView.ItemTemplate>
```

After change I can focus first element and scroll to the last element but still the last one is unfocusable.

![focused](https://user-images.githubusercontent.com/11194646/44709762-f0b65700-aa99-11e8-8885-465ef8a4fc0c.png)
![unfocused](https://user-images.githubusercontent.com/11194646/44709764-f14eed80-aa99-11e8-8960-f39707f407b3.png)

Emulator binary version: tizen-4.0-unified_20180728.1

Nuget package version: 1.0.0-pre2-00085

**Comment by jkpu** [comment]
The CircleListView's backend EFL extension has limitation in a circle wearable device.
limitation is not being focused and not being tapped on the top and bottom of the screen due to UI concept. you can check any inhouse app that has listview. They are display only 3 item in a screen, but  vertical center item is only clickable and focusable. 

For escaping this issue on CircularUI, CircularUI renderer manipulated listview. but this modification only apply default TextCell. If a user uses ViewCell or custom Header or Footer template. this issue will occur.

To avoid this inherent problem, you should specify a proper height value (120 recommended) by the ViewCell or ListView Header or Footer.

I added warnning at CircleListView guide and add HeightRequest value at each CircleListView TCs .
please refer to this PR : https://github.com/Samsung/Tizen.CircularUI/pull/107
