### ISSUE TITLE
[CircularUI][PopupEntry] Physical keyboard issue

### ISSUE THREAD

**Issue by t-zalewski** [Samsung/Tizen.CircularUI#127]
Hey,

On Tizen Emulator when you start using physical keyboard, apps are not showing on-screen keyboard but you should be allowed to type from PC keyboard(this behaviour is supported in Xamarin.Forms Entry). However, PopupEntry starts to be inaccessible and it is impossible to work with its content.

Steps to reproduce the issue:
1. Open any application on emulator where is entry field (eg. Messages) and start typing from your PC physical keyboard.
2. Go to your application with PopupEntry and try to change its text.

Results:
PopupEntry is inaccessible.

**Comment by jkpu** [comment]
What you mean that "physical keyboard" is ?  I can't find any keyboard menu or option in emulator. When I typed keyboard with my PC. It is not applied to  editfiled.

**Comment by jkpu** [comment]
CircularUI supports a developer who wants to develop Galaxy watch C# app.
So, CircularUI reference device is real Galaxy watch device , not tizen emulator. As you can see some look and behavior of emulator's UI are different to Galaxy watch device.
We think this issue is emulator only scenario. We can't find any real scenario like this issue. How could you 
insert keyboard input in real Galaxy watch device? and also, I have seen many issue on inhouse app with keyboard input like this issue. 
so close issue.
