### ISSUE TITLE
[CircleStepper]  Bug with text centering when the number of displayed characters changes

### ISSUE THREAD

**Issue by mszperna** [Samsung/Tizen.CircularUI#181]
CircleStepper has a problem with text centering when the number of displayed characters changes. This can be seen, for example, when switching from two-digit number to three-digit, like 90 to 100 (assuming that each bezel movement changes the value +/-10), when the number 100 is moved to the right, and only after switching to 110 it is centred again.

Check the application below, which reproduces the bug.
[CircleStepperIssue.zip](https://github.com/Samsung/Tizen.CircularUI/files/3044044/CircleStepperIssue.zip)

1. Move bezel clockwise until you reach 90. The number should be centered correctly.
2. Move bezel one more time, the number value will change to 100 - it will be displayed slightly on the right. The expected behavior is that number 100 is in the center.
3. Move bezel again, the value will change to 110 and the number will be centered again.

Expected behavior
CircleStepper should center the text when number of displayed characters changes.

Screenshots (the points correspond to the description in the section "Steps to reproduce")
1. 
![CircleStepper_90_correct](https://user-images.githubusercontent.com/31132452/55565950-145e1180-56fb-11e9-90de-acfeb495d763.png)

2.
Current view (BUG):
![CircleStepper_100_bug](https://user-images.githubusercontent.com/31132452/55565979-1fb13d00-56fb-11e9-8412-c3f55502c86b.png)
Expected:
![CircleStepper_100_expected](https://user-images.githubusercontent.com/31132452/55566058-3d7ea200-56fb-11e9-86de-1b8424d12d18.png)

3.
![CircleStepper_110_correct](https://user-images.githubusercontent.com/31132452/55566084-47080a00-56fb-11e9-8ae7-f7d375db828f.png)

Environment:
 - Tizen Platform Version: Tizen 5.0
 - Tizen.CircularUI Version: both 1.0.0 and 1.1.0

**Comment by jkpu** [comment]
![Tizen Emulator 5 0](https://user-images.githubusercontent.com/31116585/55603174-598a4e00-57a4-11e9-90c2-6be23932dbff.gif)

Above animation is the capture of CircleStepper behavior on Tizen emulator 5.0.
This issue is EFL native circle spinner issue. There is no text alignment in CircularUI's CircleStepper renderer.
Tizen 5.0 emulator didn't have UI verification. so there are many native UI issue.  please refer to Issue(https://github.com/Samsung/Tizen.CircularUI/issues/173)


Below animation is capture of CircleStepper  behavior(with attached CircleStepperIssue.zip) on Tizen Emulator 4.0 ( Latest internal released SDK tizen-4.0-unified_20190306.1)

![Tizen Emulator 4 0](https://user-images.githubusercontent.com/31116585/55603375-5e033680-57a5-11e9-8c45-01067ac37477.gif)

As you can see above image,  native circle spinner's UI has been changed in 4.0 . This UI concept is Tizen 2019 UX. it will be applied  Tizen 5.5 also.  But This concept will not be applied to Tizen 5.0 emulator. 
So, We recommend that you use Tizen 4.0 emulator instead of Tizen 5.0 emulator.
