### ISSUE TITLE
[InformationPopup] can not dismiss InformationPopup

### ISSUE THREAD

**Issue by sung-su** [Samsung/Tizen.CircularUI#199]
**Describe the bug**
When multiple InformationPopup has shown, sometimes can not dismiss popup via Bottom Button.

**To Reproduce**
![popup](https://user-images.githubusercontent.com/10704816/60647306-62a8bb00-9e78-11e9-89ee-f95ef3f91e51.gif)
Repeat the above action.

**Expected behavior**
Close all pop-ups.

**Screenshots**
sample project
[InformationPopupIssueSampleApp.zip](https://github.com/Samsung/Tizen.CircularUI/files/3358187/InformationPopupIssueSampleApp.zip)

**Environment (please complete the following information):**
 - Target Product : SM-R800
 - Tizen Platform Version : Tizen 4.0.0.4
 - Tizen.CircularUI Version : 1.2.0

**Comment by jkpu** [comment]
Thanks you for your issue reporting.
I had reproduced this issue using attached sample app. 
button event handler is not called because managed instance was destroy by GC but platform native widget is still displayed. so click event didn't pass to managed area.
I fixed this issue preventing unwanted removing by GC. (https://github.com/Samsung/Tizen.CircularUI/pull/200)
