### ISSUE TITLE
Circle ActionButton displayed in the middle of the page

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.CircularUI#232]
**Describe the bug**

I used directly your sample [here ](https://github.com/Samsung/Tizen.CircularUI/blob/26f327ba5c68b04578df5a63fc1c09898ea5fc3b/sample/XUIComponents/UIComponents/UIComponents/Samples/Button/BottomButton.xaml)

and result as attached image
![image](https://user-images.githubusercontent.com/10422347/75082304-3929c600-5513-11ea-810b-a4546aa3ba81.png)
 
**Expected behavior**
at the bottom
 
**Environment (please complete the following information):**
 - Target Product Emulator in the image
![image](https://user-images.githubusercontent.com/10422347/75082387-9cb3f380-5513-11ea-8aca-22c0c9ab57c4.png)

 - Tizen Platform Version 4.0
 - Tizen.CircularUI Version  1.4.0

**Comment by EmilAlipiev** [comment]
Problem was the same on Galaxy Watch Active wit 4.0.
Fix was to add    `NavigationPage.HasBackButton="False" NavigationPage.HasNavigationBar="False" `
on the CirclePage. I dont understand why it appears in the middle if i dont set those as false? I cannot see any annotation in the documentation

**Comment by jkpu** [comment]
This issue occurred due to  NavigationPage contraint in Tizen.
I added warnning statement in CirclePage/BottomButton guide. (https://github.com/Samsung/Tizen.CircularUI/pull/235)


--------------------------------------------------------------------
**WARNING: If you add CirclePage to NavigationPage stack, you should add `NavigationPage.HasNavigationBar="False"` in XAML or `NavigationPage.SetHasNavigationBar(targetPage, false)` in code for preventing abnormal behavior of bottom button. Because NavigationPage has title area and it occupied top area, it change bottom button area. This is native framework constraint.**

|NavigationPage issue screenshot | Normal behavior screenshot |
|:------------------------------:|:--------------------------------:|
|![navigationPage_Bottom_button_issue](https://user-images.githubusercontent.com/31116585/75131489-a6f20f80-5716-11ea-9d23-4de8cad2a21f.png)|![bottom_button_navigation](https://user-images.githubusercontent.com/31116585/75131468-917ce580-5716-11ea-8754-068b89c7476a.png)|


**XAML for NavigationPage**
```xml
<c:CirclePage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:c="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
             x:Class="TizenWearableXamlApp.MainPage"
             NavigationPage.HasNavigationBar="False">
```

**Code for NavigationPage**
```cs
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

           // Application.Current.MainPage = new NavigationPage(new MainPage());
            var page =new MainPage();
            NavigationPage.SetHasNavigationBar(page, false);
            Application.Current.MainPage = new NavigationPage(page);
        }
```

**Comment by jkpu** [comment]
Issue was fixed in https://github.com/Samsung/Tizen.CircularUI/pull/237
