### ISSUE TITLE
It is not possible to use certain characters in Text properties

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#243]
**Describe the bug**
I have come across a number of problems trying to add extended ascii characters to Text Properties of various objects.

For example A CirclePage ActionButton Text property will not display an ampersand
This is true for other string characters for other object Text properties as well as a new line character.
Ive found a work around for the new line is to use html eescape break sequance, but other html escape sequances dont seem to work.

This is reproducible on the watch emulator, do not have hardware.

**To Reproduce**
1. Create a CirclePage
2. Create an ActionButton
3. Write an ampersand to its text property
4. See any text including and after the ampersand does not display

**Expected behavior**
Expect to see any .net string set to a Text property displayed 
Or at least a listing of escape sequances that will substitue.

**Screenshots**
Action button set with text that includes ampersand
`ActionButton.Text = "Add & Connect";`

![image](https://user-images.githubusercontent.com/13371986/75311663-8d8bb900-5825-11ea-8bde-d76cc7b7cce7.png)

Observe all characters from ampersand on do not display.

**Environment (please complete the following information):**
 - Target Product Emulator 4.0 Release on 3.6 SDK (2.8.0.24)
 - Tizen Platform Version [Tizen 4.0.0]
 - Tizen.CircularUI Version [e.g. 1.4.0]

**Additional context**
Seemingly there is conflict with web UI.

**Comment by jkpu** [comment]
This issue was fixed in #244 , and it will be included next Nuget package release.

But Tizen native bottom button's constraint. Bottom button only support single Line text.
So. If you add newLine and second line text, the second line text is not displayed in bottom button.

![avtionbutton_ampersand](https://user-images.githubusercontent.com/31116585/75315717-ce77e200-58a6-11ea-9608-35c3ee3fe86d.png)

![avtionbutton_special_characters](https://user-images.githubusercontent.com/31116585/75315742-dd5e9480-58a6-11ea-907b-3c4f19dd0bbe.png)

**Comment by axa88** [comment]
Having it fixed in future release solves this issue, though I will say using html escape sequence such as
`&amp`
Surely did not fix the issue.  (At least not in the emulator version I listed in the report)
