### ISSUE TITLE
CircleListView. Can't set focus to first element, when it has small height

### ISSUE THREAD

**Issue by MaxGsomGsom** [Samsung/Tizen.CircularUI#313]
CircleListView. Can't set focus to first element, when `HasUnevenRows = true` and size of first element is small (for example when height of element less than 1/4 of display height, picture 1). Focus is always set to second element. When element is big enough (height is bigger the 1/2 of screen, picture 2), focusing works as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/5579512/82728098-ef5da100-9cf6-11ea-998e-1bc22c4ca27d.png)

![image](https://user-images.githubusercontent.com/5579512/82728111-09977f00-9cf7-11ea-85fb-ecd0a2a2efbf.png)

**Environment (please complete the following information):**
- Tizen 4 Emulator
- Tizen.CircularUI 1.5 pre
- Tizen.NET 6.0.0.14995
- Xamarin Forms 4.6.0.726

**Comment by jkpu** [comment]
This issue is due to Tizen native UIFW ListView restriction. native UIFW is considered that the first and last items are blank or header/footer of listview. so if user insert list item in first or last of listview, focus is not working and click event is not occur.
For avoiding this issue, Tizen.CircularUI add a blank item automatically when threre is no header or footer in CircleListview. but it will not work if item height is too small. 
We recommand item height is over 120 ( height is 1/3 of screen size).
