### ISSUE TITLE
[CircleListView] Change highlighting effect

### ISSUE THREAD

**Issue by Machinero** [Samsung/Tizen.CircularUI#327]
Is there possible way to change highlight effect in the CircleListView like in the following image?

![my_image](https://d3unf4s5rp9dfh.cloudfront.net/sd2_images/gear/design/UI_11.3.2.png)

**Comment by rookiejava** [comment]
Hi @Machinero 👋, thank you for reaching out.

The effect of the image you attached is exactly the same as the current behavior of the ListView (CircleListView as well) on the Galaxy Watch. Could you tell me more about what you want?

**Comment by Machinero** [comment]
Thank you for response @rookiejava .

I have created the CircleListView at Emulator 5.5 and the effect is a bit different than effect that i pointed in the last comment.
![image](https://user-images.githubusercontent.com/25220104/84989984-c89f5880-b144-11ea-996e-025618c8a6f2.png)

My goal is to achieve effect like in the following image. Is it possible?
![image](https://user-images.githubusercontent.com/25220104/84991404-c0e0b380-b146-11ea-8abf-544159941440.png)


Could you also answer for the following questions?
1. Why CircleListView cut a perimeter of the top and bottom elements on the screen at emulator? This effect doesn't occur on Emulator 4.0.
2. Is it possible to disable scroll bar in CircleListView?

**Comment by rookiejava** [comment]
Since the UX policy of each platform version (4.0, 5.0, 5.5 ...) is different, it may look different for each version. I think it will look like what you would expect when the latest version of the emulator image is published. (I can't decide the detailed schedule, but I expect it to be published soon.)

> Is it possible to disable scroll bar in CircleListView?

If you use the latest version(1.5.0) of the Circular UI, you can control with `ListView.VerticalScrollBarVisibility` (or `istView.HorizontalScrollBarVisibility`).
