### ISSUE TITLE
Sample code for CarouselView + IndicatorView on Tizen

### ISSUE THREAD

**Issue by matthewkrueger** [Samsung/Tizen.CircularUI#346]
The documentation mentions that IndexPage is deprecated and to use CarouselView + IndicatorView instead.

The problem is there are no examples of how to accomplish this. I've tried to figure it out using other examples from Xaramin.Forms samples (not tizen-specific) and I am able to get a CarouselView, but the indicators are not showing on top of the screen, and they are not rounding to fit the circular watch screen like IndexPage does.

Please update the documentation and sample project to provide an example of how to accomplish CarouselView + IndicatorView on a Tizen watch.

For now I'm just using IndexPage, but as this is a brand new app I'd really like to not release this using deprecated libraries.

Thanks!

**Comment by Machinero** [comment]
@matthewkrueger 
Have you tried to use the example from issue #330?

**Comment by myroot** [comment]
Here is a sample code for CarouselView and IndicatorView

![image](https://user-images.githubusercontent.com/1029155/93727905-6862fb80-fbf8-11ea-86f6-7325e999b555.png)

https://gist.github.com/myroot/e5e9f88f46ade609ef51fecf917b322c
[CarouselViewSample.zip](https://github.com/Samsung/Tizen.CircularUI/files/5253150/CarouselViewSample.zip)

**Comment by EmilAlipiev** [comment]
what is the reason IndexPage was deprecated? wasn't it a better way of carouselview?

**Comment by rookiejava** [comment]
Hi @EmilAlipiev! Happy new year!

The main reason is that `IndexPage` is a `MultiPage` that does not provide special features, so there is no need to provide it as a separate class. If you want to use a `Page` rather than a `View`, I recommend using `CarouselPage`. (Both are almost the same)

See the xamarin guide below for more details on why `CarouselView` replaces `CarouselPage`.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/carousel-page
