### ISSUE TITLE
Going forward?

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#372]
I was using Tizen and the CircularUI to develop on the galaxy watch... 
Started a new job and came back nearly 2 years later and find my devices running WearOS 3.5 and this project dead?

What is the way forward development Circular Wearable apps for the Galaxy Watch in .NET?

**Comment by rookiejava** [comment]
Hi @axa88,
As you may already know, the latest Galaxy Watch series (since Galaxy Watch 4) has been using Wear OS, not Tizen.
Since `Tizen.CircularUI` project was created to help develop the Galaxy Watch app based on Tizen, we recommend that you refer to https://developer.android.com/training/wearables for building Galaxy Watch app based on Wear OS.

**Comment by axa88** [comment]
@rookiejava 
A large appeal of Tizen.NET was being able to use .NET in c#.
A large appeal of CircularUI was an api for circular UIs.

Will none of this be brought forward for use someplace else? .NET? MAUI?
What a shame to lose this resource.
